# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rmcs_resource_api import data_pb2 as rmcs__resource__api_dot_data__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rmcs_resource_api/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadData = channel.unary_unary(
                '/data.DataService/ReadData',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataReadResponse.FromString,
                _registered_method=True)
        self.ListDataByTime = channel.unary_unary(
                '/data.DataService/ListDataByTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByLastTime = channel.unary_unary(
                '/data.DataService/ListDataByLastTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByRangeTime = channel.unary_unary(
                '/data.DataService/ListDataByRangeTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataRange.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByNumberBefore = channel.unary_unary(
                '/data.DataService/ListDataByNumberBefore',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByNumberAfter = channel.unary_unary(
                '/data.DataService/ListDataByNumberAfter',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ReadDataTimestamp = channel.unary_unary(
                '/data.DataService/ReadDataTimestamp',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.TimestampReadResponse.FromString,
                _registered_method=True)
        self.ListDataTimestampByLastTime = channel.unary_unary(
                '/data.DataService/ListDataTimestampByLastTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListDataTimestampByRangeTime = channel.unary_unary(
                '/data.DataService/ListDataTimestampByRangeTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataRange.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.CreateData = channel.unary_unary(
                '/data.DataService/CreateData',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSchema.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataChangeResponse.FromString,
                _registered_method=True)
        self.DeleteData = channel.unary_unary(
                '/data.DataService/DeleteData',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataChangeResponse.FromString,
                _registered_method=True)
        self.CountData = channel.unary_unary(
                '/data.DataService/CountData',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataCount.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataByLastTime = channel.unary_unary(
                '/data.DataService/CountDataByLastTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataCount.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataByRangeTime = channel.unary_unary(
                '/data.DataService/CountDataByRangeTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataCount.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.ListDataBySetTime = channel.unary_unary(
                '/data.DataService/ListDataBySetTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataBySetLastTime = channel.unary_unary(
                '/data.DataService/ListDataBySetLastTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataBySetRangeTime = channel.unary_unary(
                '/data.DataService/ListDataBySetRangeTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetRange.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataBySetNumberBefore = channel.unary_unary(
                '/data.DataService/ListDataBySetNumberBefore',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataBySetNumberAfter = channel.unary_unary(
                '/data.DataService/ListDataBySetNumberAfter',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ReadDataSet = channel.unary_unary(
                '/data.DataService/ReadDataSet',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataSetReadResponse.FromString,
                _registered_method=True)
        self.ListDataSetByTime = channel.unary_unary(
                '/data.DataService/ListDataSetByTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ListDataSetByLastTime = channel.unary_unary(
                '/data.DataService/ListDataSetByLastTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ListDataSetByRangeTime = channel.unary_unary(
                '/data.DataService/ListDataSetByRangeTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetRange.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ListDataSetByNumberBefore = channel.unary_unary(
                '/data.DataService/ListDataSetByNumberBefore',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ListDataSetByNumberAfter = channel.unary_unary(
                '/data.DataService/ListDataSetByNumberAfter',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ReadDataSetTimestamp = channel.unary_unary(
                '/data.DataService/ReadDataSetTimestamp',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.TimestampReadResponse.FromString,
                _registered_method=True)
        self.ListDataSetTimestampByLastTime = channel.unary_unary(
                '/data.DataService/ListDataSetTimestampByLastTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListDataSetTimestampByRangeTime = channel.unary_unary(
                '/data.DataService/ListDataSetTimestampByRangeTime',
                request_serializer=rmcs__resource__api_dot_data__pb2.DataSetRange.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByLastTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByRangeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByNumberBefore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByNumberAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataTimestampByLastTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataTimestampByRangeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataByLastTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataByRangeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataBySetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataBySetLastTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataBySetRangeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataBySetNumberBefore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataBySetNumberAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByLastTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByRangeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByNumberBefore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByNumberAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataSetTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetTimestampByLastTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetTimestampByRangeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadData,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataId.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataReadResponse.SerializeToString,
            ),
            'ListDataByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByLastTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByLastTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByRangeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByRangeTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataRange.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByNumberBefore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByNumberBefore,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByNumberAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByNumberAfter,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ReadDataTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDataTimestamp,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataId.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.TimestampReadResponse.SerializeToString,
            ),
            'ListDataTimestampByLastTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataTimestampByLastTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListDataTimestampByRangeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataTimestampByRangeTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataRange.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'CreateData': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateData,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSchema.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataChangeResponse.SerializeToString,
            ),
            'DeleteData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteData,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataId.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataChangeResponse.SerializeToString,
            ),
            'CountData': grpc.unary_unary_rpc_method_handler(
                    servicer.CountData,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataCount.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataByLastTime': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataByLastTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataCount.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataByRangeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataByRangeTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataCount.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'ListDataBySetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataBySetTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataBySetLastTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataBySetLastTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataBySetRangeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataBySetRangeTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetRange.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataBySetNumberBefore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataBySetNumberBefore,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataBySetNumberAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataBySetNumberAfter,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ReadDataSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDataSet,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetId.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataSetReadResponse.SerializeToString,
            ),
            'ListDataSetByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ListDataSetByLastTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByLastTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ListDataSetByRangeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByRangeTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetRange.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ListDataSetByNumberBefore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByNumberBefore,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ListDataSetByNumberAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByNumberAfter,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ReadDataSetTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDataSetTimestamp,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetId.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.TimestampReadResponse.SerializeToString,
            ),
            'ListDataSetTimestampByLastTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetTimestampByLastTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetTime.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListDataSetTimestampByRangeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetTimestampByRangeTime,
                    request_deserializer=rmcs__resource__api_dot_data__pb2.DataSetRange.FromString,
                    response_serializer=rmcs__resource__api_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadData',
            rmcs__resource__api_dot_data__pb2.DataId.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByTime',
            rmcs__resource__api_dot_data__pb2.DataTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByLastTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByLastTime',
            rmcs__resource__api_dot_data__pb2.DataTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByRangeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByRangeTime',
            rmcs__resource__api_dot_data__pb2.DataRange.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByNumberBefore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByNumberBefore',
            rmcs__resource__api_dot_data__pb2.DataNumber.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByNumberAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByNumberAfter',
            rmcs__resource__api_dot_data__pb2.DataNumber.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadDataTimestamp',
            rmcs__resource__api_dot_data__pb2.DataId.SerializeToString,
            rmcs__resource__api_dot_data__pb2.TimestampReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataTimestampByLastTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataTimestampByLastTime',
            rmcs__resource__api_dot_data__pb2.DataTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataTimestampByRangeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataTimestampByRangeTime',
            rmcs__resource__api_dot_data__pb2.DataRange.SerializeToString,
            rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CreateData',
            rmcs__resource__api_dot_data__pb2.DataSchema.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/DeleteData',
            rmcs__resource__api_dot_data__pb2.DataId.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountData',
            rmcs__resource__api_dot_data__pb2.DataCount.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataByLastTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataByLastTime',
            rmcs__resource__api_dot_data__pb2.DataCount.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataByRangeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataByRangeTime',
            rmcs__resource__api_dot_data__pb2.DataCount.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataBySetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataBySetTime',
            rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataBySetLastTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataBySetLastTime',
            rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataBySetRangeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataBySetRangeTime',
            rmcs__resource__api_dot_data__pb2.DataSetRange.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataBySetNumberBefore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataBySetNumberBefore',
            rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataBySetNumberAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataBySetNumberAfter',
            rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadDataSet',
            rmcs__resource__api_dot_data__pb2.DataSetId.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataSetReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByTime',
            rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByLastTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByLastTime',
            rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByRangeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByRangeTime',
            rmcs__resource__api_dot_data__pb2.DataSetRange.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByNumberBefore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByNumberBefore',
            rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByNumberAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByNumberAfter',
            rmcs__resource__api_dot_data__pb2.DataSetNumber.SerializeToString,
            rmcs__resource__api_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataSetTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadDataSetTimestamp',
            rmcs__resource__api_dot_data__pb2.DataSetId.SerializeToString,
            rmcs__resource__api_dot_data__pb2.TimestampReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetTimestampByLastTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetTimestampByLastTime',
            rmcs__resource__api_dot_data__pb2.DataSetTime.SerializeToString,
            rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetTimestampByRangeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetTimestampByRangeTime',
            rmcs__resource__api_dot_data__pb2.DataSetRange.SerializeToString,
            rmcs__resource__api_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
