# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rmcs_resource_api import device_pb2 as rmcs__resource__api_dot_device__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rmcs_resource_api/device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadDevice = channel.unary_unary(
                '/device.DeviceService/ReadDevice',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceReadResponse.FromString,
                _registered_method=True)
        self.ReadDeviceBySn = channel.unary_unary(
                '/device.DeviceService/ReadDeviceBySn',
                request_serializer=rmcs__resource__api_dot_device__pb2.SerialNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceReadResponse.FromString,
                _registered_method=True)
        self.ListDeviceByIds = channel.unary_unary(
                '/device.DeviceService/ListDeviceByIds',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceIds.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
                _registered_method=True)
        self.ListDeviceByGateway = channel.unary_unary(
                '/device.DeviceService/ListDeviceByGateway',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
                _registered_method=True)
        self.ListDeviceByType = channel.unary_unary(
                '/device.DeviceService/ListDeviceByType',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
                _registered_method=True)
        self.ListDeviceByName = channel.unary_unary(
                '/device.DeviceService/ListDeviceByName',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceName.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
                _registered_method=True)
        self.ListDeviceOption = channel.unary_unary(
                '/device.DeviceService/ListDeviceOption',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceOption.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
                _registered_method=True)
        self.CreateDevice = channel.unary_unary(
                '/device.DeviceService/CreateDevice',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceSchema.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceCreateResponse.FromString,
                _registered_method=True)
        self.UpdateDevice = channel.unary_unary(
                '/device.DeviceService/UpdateDevice',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceUpdate.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceChangeResponse.FromString,
                _registered_method=True)
        self.DeleteDevice = channel.unary_unary(
                '/device.DeviceService/DeleteDevice',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.DeviceChangeResponse.FromString,
                _registered_method=True)
        self.ReadGateway = channel.unary_unary(
                '/device.DeviceService/ReadGateway',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayReadResponse.FromString,
                _registered_method=True)
        self.ReadGatewayBySn = channel.unary_unary(
                '/device.DeviceService/ReadGatewayBySn',
                request_serializer=rmcs__resource__api_dot_device__pb2.SerialNumber.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayReadResponse.FromString,
                _registered_method=True)
        self.ListGatewayByIds = channel.unary_unary(
                '/device.DeviceService/ListGatewayByIds',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayIds.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
                _registered_method=True)
        self.ListGatewayByType = channel.unary_unary(
                '/device.DeviceService/ListGatewayByType',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
                _registered_method=True)
        self.ListGatewayByName = channel.unary_unary(
                '/device.DeviceService/ListGatewayByName',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayName.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
                _registered_method=True)
        self.ListGatewayOption = channel.unary_unary(
                '/device.DeviceService/ListGatewayOption',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayOption.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
                _registered_method=True)
        self.CreateGateway = channel.unary_unary(
                '/device.DeviceService/CreateGateway',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewaySchema.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayCreateResponse.FromString,
                _registered_method=True)
        self.UpdateGateway = channel.unary_unary(
                '/device.DeviceService/UpdateGateway',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayUpdate.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayChangeResponse.FromString,
                _registered_method=True)
        self.DeleteGateway = channel.unary_unary(
                '/device.DeviceService/DeleteGateway',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.GatewayChangeResponse.FromString,
                _registered_method=True)
        self.ReadDeviceConfig = channel.unary_unary(
                '/device.DeviceService/ReadDeviceConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigReadResponse.FromString,
                _registered_method=True)
        self.ListDeviceConfig = channel.unary_unary(
                '/device.DeviceService/ListDeviceConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.DeviceId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigListResponse.FromString,
                _registered_method=True)
        self.CreateDeviceConfig = channel.unary_unary(
                '/device.DeviceService/CreateDeviceConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigSchema.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigCreateResponse.FromString,
                _registered_method=True)
        self.UpdateDeviceConfig = channel.unary_unary(
                '/device.DeviceService/UpdateDeviceConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigUpdate.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
                _registered_method=True)
        self.DeleteDeviceConfig = channel.unary_unary(
                '/device.DeviceService/DeleteDeviceConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
                _registered_method=True)
        self.ReadGatewayConfig = channel.unary_unary(
                '/device.DeviceService/ReadGatewayConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigReadResponse.FromString,
                _registered_method=True)
        self.ListGatewayConfig = channel.unary_unary(
                '/device.DeviceService/ListGatewayConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigListResponse.FromString,
                _registered_method=True)
        self.CreateGatewayConfig = channel.unary_unary(
                '/device.DeviceService/CreateGatewayConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigSchema.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigCreateResponse.FromString,
                _registered_method=True)
        self.UpdateGatewayConfig = channel.unary_unary(
                '/device.DeviceService/UpdateGatewayConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigUpdate.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
                _registered_method=True)
        self.DeleteGatewayConfig = channel.unary_unary(
                '/device.DeviceService/DeleteGatewayConfig',
                request_serializer=rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
                _registered_method=True)
        self.ReadType = channel.unary_unary(
                '/device.DeviceService/ReadType',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeReadResponse.FromString,
                _registered_method=True)
        self.ListTypeByIds = channel.unary_unary(
                '/device.DeviceService/ListTypeByIds',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeIds.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeListResponse.FromString,
                _registered_method=True)
        self.ListTypeByName = channel.unary_unary(
                '/device.DeviceService/ListTypeByName',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeName.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeListResponse.FromString,
                _registered_method=True)
        self.ListTypeOption = channel.unary_unary(
                '/device.DeviceService/ListTypeOption',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeOption.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeListResponse.FromString,
                _registered_method=True)
        self.CreateType = channel.unary_unary(
                '/device.DeviceService/CreateType',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeSchema.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeCreateResponse.FromString,
                _registered_method=True)
        self.UpdateType = channel.unary_unary(
                '/device.DeviceService/UpdateType',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeUpdate.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
                _registered_method=True)
        self.DeleteType = channel.unary_unary(
                '/device.DeviceService/DeleteType',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
                _registered_method=True)
        self.AddTypeModel = channel.unary_unary(
                '/device.DeviceService/AddTypeModel',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeModel.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
                _registered_method=True)
        self.RemoveTypeModel = channel.unary_unary(
                '/device.DeviceService/RemoveTypeModel',
                request_serializer=rmcs__resource__api_dot_device__pb2.TypeModel.SerializeToString,
                response_deserializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDeviceBySn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeviceByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeviceByGateway(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeviceByType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeviceByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeviceOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadGateway(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadGatewayBySn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGatewayByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGatewayByType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGatewayByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGatewayOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGateway(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGateway(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGateway(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDeviceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeviceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDeviceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDeviceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDeviceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadGatewayConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGatewayConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGatewayConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGatewayConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGatewayConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTypeByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTypeByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTypeOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTypeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTypeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDevice,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceReadResponse.SerializeToString,
            ),
            'ReadDeviceBySn': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDeviceBySn,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.SerialNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceReadResponse.SerializeToString,
            ),
            'ListDeviceByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeviceByIds,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceIds.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.SerializeToString,
            ),
            'ListDeviceByGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeviceByGateway,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.SerializeToString,
            ),
            'ListDeviceByType': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeviceByType,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.SerializeToString,
            ),
            'ListDeviceByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeviceByName,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceName.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.SerializeToString,
            ),
            'ListDeviceOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeviceOption,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceOption.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceListResponse.SerializeToString,
            ),
            'CreateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDevice,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceSchema.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceCreateResponse.SerializeToString,
            ),
            'UpdateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDevice,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceUpdate.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceChangeResponse.SerializeToString,
            ),
            'DeleteDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDevice,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.DeviceChangeResponse.SerializeToString,
            ),
            'ReadGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadGateway,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayReadResponse.SerializeToString,
            ),
            'ReadGatewayBySn': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadGatewayBySn,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.SerialNumber.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayReadResponse.SerializeToString,
            ),
            'ListGatewayByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGatewayByIds,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayIds.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.SerializeToString,
            ),
            'ListGatewayByType': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGatewayByType,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.SerializeToString,
            ),
            'ListGatewayByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGatewayByName,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayName.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.SerializeToString,
            ),
            'ListGatewayOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGatewayOption,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayOption.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayListResponse.SerializeToString,
            ),
            'CreateGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGateway,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewaySchema.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayCreateResponse.SerializeToString,
            ),
            'UpdateGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGateway,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayUpdate.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayChangeResponse.SerializeToString,
            ),
            'DeleteGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGateway,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.GatewayChangeResponse.SerializeToString,
            ),
            'ReadDeviceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDeviceConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigReadResponse.SerializeToString,
            ),
            'ListDeviceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeviceConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.DeviceId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigListResponse.SerializeToString,
            ),
            'CreateDeviceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDeviceConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigSchema.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigCreateResponse.SerializeToString,
            ),
            'UpdateDeviceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDeviceConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigUpdate.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.SerializeToString,
            ),
            'DeleteDeviceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDeviceConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.SerializeToString,
            ),
            'ReadGatewayConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadGatewayConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigReadResponse.SerializeToString,
            ),
            'ListGatewayConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGatewayConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.GatewayId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigListResponse.SerializeToString,
            ),
            'CreateGatewayConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGatewayConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigSchema.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigCreateResponse.SerializeToString,
            ),
            'UpdateGatewayConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGatewayConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigUpdate.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.SerializeToString,
            ),
            'DeleteGatewayConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGatewayConfig,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.ConfigId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.SerializeToString,
            ),
            'ReadType': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadType,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeReadResponse.SerializeToString,
            ),
            'ListTypeByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTypeByIds,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeIds.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeListResponse.SerializeToString,
            ),
            'ListTypeByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTypeByName,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeName.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeListResponse.SerializeToString,
            ),
            'ListTypeOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTypeOption,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeOption.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeListResponse.SerializeToString,
            ),
            'CreateType': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateType,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeSchema.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeCreateResponse.SerializeToString,
            ),
            'UpdateType': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateType,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeUpdate.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.SerializeToString,
            ),
            'DeleteType': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteType,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeId.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.SerializeToString,
            ),
            'AddTypeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTypeModel,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeModel.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.SerializeToString,
            ),
            'RemoveTypeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTypeModel,
                    request_deserializer=rmcs__resource__api_dot_device__pb2.TypeModel.FromString,
                    response_serializer=rmcs__resource__api_dot_device__pb2.TypeChangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ReadDevice',
            rmcs__resource__api_dot_device__pb2.DeviceId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDeviceBySn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ReadDeviceBySn',
            rmcs__resource__api_dot_device__pb2.SerialNumber.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeviceByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListDeviceByIds',
            rmcs__resource__api_dot_device__pb2.DeviceIds.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeviceByGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListDeviceByGateway',
            rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeviceByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListDeviceByType',
            rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeviceByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListDeviceByName',
            rmcs__resource__api_dot_device__pb2.DeviceName.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeviceOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListDeviceOption',
            rmcs__resource__api_dot_device__pb2.DeviceOption.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/CreateDevice',
            rmcs__resource__api_dot_device__pb2.DeviceSchema.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/UpdateDevice',
            rmcs__resource__api_dot_device__pb2.DeviceUpdate.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/DeleteDevice',
            rmcs__resource__api_dot_device__pb2.DeviceId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.DeviceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ReadGateway',
            rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadGatewayBySn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ReadGatewayBySn',
            rmcs__resource__api_dot_device__pb2.SerialNumber.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGatewayByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListGatewayByIds',
            rmcs__resource__api_dot_device__pb2.GatewayIds.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGatewayByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListGatewayByType',
            rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGatewayByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListGatewayByName',
            rmcs__resource__api_dot_device__pb2.GatewayName.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGatewayOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListGatewayOption',
            rmcs__resource__api_dot_device__pb2.GatewayOption.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/CreateGateway',
            rmcs__resource__api_dot_device__pb2.GatewaySchema.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/UpdateGateway',
            rmcs__resource__api_dot_device__pb2.GatewayUpdate.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/DeleteGateway',
            rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.GatewayChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDeviceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ReadDeviceConfig',
            rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeviceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListDeviceConfig',
            rmcs__resource__api_dot_device__pb2.DeviceId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDeviceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/CreateDeviceConfig',
            rmcs__resource__api_dot_device__pb2.ConfigSchema.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDeviceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/UpdateDeviceConfig',
            rmcs__resource__api_dot_device__pb2.ConfigUpdate.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDeviceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/DeleteDeviceConfig',
            rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadGatewayConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ReadGatewayConfig',
            rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGatewayConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListGatewayConfig',
            rmcs__resource__api_dot_device__pb2.GatewayId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGatewayConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/CreateGatewayConfig',
            rmcs__resource__api_dot_device__pb2.ConfigSchema.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGatewayConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/UpdateGatewayConfig',
            rmcs__resource__api_dot_device__pb2.ConfigUpdate.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGatewayConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/DeleteGatewayConfig',
            rmcs__resource__api_dot_device__pb2.ConfigId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.ConfigChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ReadType',
            rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTypeByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListTypeByIds',
            rmcs__resource__api_dot_device__pb2.TypeIds.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTypeByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListTypeByName',
            rmcs__resource__api_dot_device__pb2.TypeName.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTypeOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/ListTypeOption',
            rmcs__resource__api_dot_device__pb2.TypeOption.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/CreateType',
            rmcs__resource__api_dot_device__pb2.TypeSchema.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/UpdateType',
            rmcs__resource__api_dot_device__pb2.TypeUpdate.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/DeleteType',
            rmcs__resource__api_dot_device__pb2.TypeId.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTypeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/AddTypeModel',
            rmcs__resource__api_dot_device__pb2.TypeModel.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTypeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceService/RemoveTypeModel',
            rmcs__resource__api_dot_device__pb2.TypeModel.SerializeToString,
            rmcs__resource__api_dot_device__pb2.TypeChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
