# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import log_pb2 as log__pb2


class LogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadLog = channel.unary_unary(
                '/log.LogService/ReadLog',
                request_serializer=log__pb2.LogId.SerializeToString,
                response_deserializer=log__pb2.LogReadResponse.FromString,
                )
        self.ListLogByTime = channel.unary_unary(
                '/log.LogService/ListLogByTime',
                request_serializer=log__pb2.LogTime.SerializeToString,
                response_deserializer=log__pb2.LogListResponse.FromString,
                )
        self.ListLogByLastTime = channel.unary_unary(
                '/log.LogService/ListLogByLastTime',
                request_serializer=log__pb2.LogTime.SerializeToString,
                response_deserializer=log__pb2.LogListResponse.FromString,
                )
        self.ListLogByRangeTime = channel.unary_unary(
                '/log.LogService/ListLogByRangeTime',
                request_serializer=log__pb2.LogRange.SerializeToString,
                response_deserializer=log__pb2.LogListResponse.FromString,
                )
        self.CreateLog = channel.unary_unary(
                '/log.LogService/CreateLog',
                request_serializer=log__pb2.LogSchema.SerializeToString,
                response_deserializer=log__pb2.LogChangeResponse.FromString,
                )
        self.UpdateLog = channel.unary_unary(
                '/log.LogService/UpdateLog',
                request_serializer=log__pb2.LogUpdate.SerializeToString,
                response_deserializer=log__pb2.LogChangeResponse.FromString,
                )
        self.DeleteLog = channel.unary_unary(
                '/log.LogService/DeleteLog',
                request_serializer=log__pb2.LogId.SerializeToString,
                response_deserializer=log__pb2.LogChangeResponse.FromString,
                )


class LogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLogByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLogByLastTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLogByRangeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLog,
                    request_deserializer=log__pb2.LogId.FromString,
                    response_serializer=log__pb2.LogReadResponse.SerializeToString,
            ),
            'ListLogByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLogByTime,
                    request_deserializer=log__pb2.LogTime.FromString,
                    response_serializer=log__pb2.LogListResponse.SerializeToString,
            ),
            'ListLogByLastTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLogByLastTime,
                    request_deserializer=log__pb2.LogTime.FromString,
                    response_serializer=log__pb2.LogListResponse.SerializeToString,
            ),
            'ListLogByRangeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLogByRangeTime,
                    request_deserializer=log__pb2.LogRange.FromString,
                    response_serializer=log__pb2.LogListResponse.SerializeToString,
            ),
            'CreateLog': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLog,
                    request_deserializer=log__pb2.LogSchema.FromString,
                    response_serializer=log__pb2.LogChangeResponse.SerializeToString,
            ),
            'UpdateLog': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLog,
                    request_deserializer=log__pb2.LogUpdate.FromString,
                    response_serializer=log__pb2.LogChangeResponse.SerializeToString,
            ),
            'DeleteLog': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLog,
                    request_deserializer=log__pb2.LogId.FromString,
                    response_serializer=log__pb2.LogChangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'log.LogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogService/ReadLog',
            log__pb2.LogId.SerializeToString,
            log__pb2.LogReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListLogByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogService/ListLogByTime',
            log__pb2.LogTime.SerializeToString,
            log__pb2.LogListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListLogByLastTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogService/ListLogByLastTime',
            log__pb2.LogTime.SerializeToString,
            log__pb2.LogListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListLogByRangeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogService/ListLogByRangeTime',
            log__pb2.LogRange.SerializeToString,
            log__pb2.LogListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogService/CreateLog',
            log__pb2.LogSchema.SerializeToString,
            log__pb2.LogChangeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogService/UpdateLog',
            log__pb2.LogUpdate.SerializeToString,
            log__pb2.LogChangeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log.LogService/DeleteLog',
            log__pb2.LogId.SerializeToString,
            log__pb2.LogChangeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
